###
POST http://localhost:5000/stories
Content-Type: application/json

{   
    "title": "Story Z",
    "body":"body z",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZWJiMDE3MzQ5YWU0OTYxNGM2YWFkYjIiLCJ1c2VyX25hbWUiOiJBIiwiaXNBZG1pbiI6ZmFsc2UsImVtYWlsIjoiYWFAdGVzdC5jb20iLCJpYXQiOjE1ODk0MzM2NDAsImV4cCI6MTU4OTUyMDA0MH0.hVGQm9nLVxdpEdmcSmD02VsV4saedrPLSuUc_HQgkhI"
}

###
DELETE http://localhost:5000/stories
Content-Type: application/json

{
    "_id": "5ebcd54449e41531708b360a",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZWJiMDE3MzQ5YWU0OTYxNGM2YWFkYjIiLCJ1c2VyX25hbWUiOiJBIiwiaXNBZG1pbiI6ZmFsc2UsImVtYWlsIjoiYWFAdGVzdC5jb20iLCJpYXQiOjE1ODk0MzM2NDAsImV4cCI6MTU4OTUyMDA0MH0.hVGQm9nLVxdpEdmcSmD02VsV4saedrPLSuUc_HQgkhI"
}

###
//Delete by some other user
DELETE http://localhost:5000/stories
Content-Type: application/json

{
    "_id": "5ebad6ee8005d920507dbdad",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZWJiMDE4MDQ5YWU0OTYxNGM2YWFkYjMiLCJ1c2VyX25hbWUiOiJCIiwiaXNBZG1pbiI6ZmFsc2UsImVtYWlsIjoiYmJAdGVzdC5jb20iLCJpYXQiOjE1ODk0MDE2OTQsImV4cCI6MTU4OTQ4ODA5NH0.ILXiq1oWoxl5_O-Q5S0dQWJCiA5OQC2DvRf8YxkfDTA"
}

###
//Delete by admin
DELETE http://localhost:5000/stories
Content-Type: application/json

{
    "_id": "5ebc4fb2b7c08c012c338a63",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZWJiMDE3MzQ5YWU0OTYxNGM2YWFkYjIiLCJ1c2VyX25hbWUiOiJBIiwiaXNBZG1pbiI6ZmFsc2UsImVtYWlsIjoiYWFAdGVzdC5jb20iLCJpYXQiOjE1ODk0MzM2NDAsImV4cCI6MTU4OTUyMDA0MH0.hVGQm9nLVxdpEdmcSmD02VsV4saedrPLSuUc_HQgkhI"
}
###
GET http://localhost:5000/stories
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZWJiMDE3MzQ5YWU0OTYxNGM2YWFkYjIiLCJ1c2VyX25hbWUiOiJBIiwiZW1haWwiOiJhYUB0ZXN0LmNvbSIsImlhdCI6MTU4OTM4OTY4NiwiZXhwIjoxNTg5NDc2MDg2fQ.ab4tF4UORaqYJWO-0Firia_R8zkASYKtHeaNUSkXdPE

###
GET http://localhost:5000/stories/author?author=Dhas&page=1&limit=3

###
PUT http://localhost:5000/stories
Content-Type: application/json

{
    "title": "Work 1",
    "body":"work 1",
    "_id": "5ebc4fb2b7c08c012c338a63",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZWJiMDE3MzQ5YWU0OTYxNGM2YWFkYjIiLCJ1c2VyX25hbWUiOiJBIiwiaXNBZG1pbiI6ZmFsc2UsImVtYWlsIjoiYWFAdGVzdC5jb20iLCJpYXQiOjE1ODkzOTkzODUsImV4cCI6MTU4OTQ4NTc4NX0.G-rs0PQeA5MfzqEG2TxIUgnDbne4QA6yCfqevApm2zE"
}

###
//Update by another user
PUT http://localhost:5000/stories
Content-Type: application/json

{
    "title": "Work 1",
    "body":"work 1",
    "_id": "5ebc4fb2b7c08c012c338a63",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZWJiMDE4MDQ5YWU0OTYxNGM2YWFkYjMiLCJ1c2VyX25hbWUiOiJCIiwiaXNBZG1pbiI6ZmFsc2UsImVtYWlsIjoiYmJAdGVzdC5jb20iLCJpYXQiOjE1ODk0MDE2OTQsImV4cCI6MTU4OTQ4ODA5NH0.ILXiq1oWoxl5_O-Q5S0dQWJCiA5OQC2DvRf8YxkfDTA"
}

###
//Update by another user
PUT http://localhost:5000/stories
Content-Type: application/json

{
    "title": "Work 1ad",
    "body":"work 1ad",
    "_id": "5ebcd54449e41531708b360a",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZWJiMDE3MzQ5YWU0OTYxNGM2YWFkYjIiLCJ1c2VyX25hbWUiOiJBIiwiaXNBZG1pbiI6ZmFsc2UsImVtYWlsIjoiYWFAdGVzdC5jb20iLCJpYXQiOjE1ODk0MzM2NDAsImV4cCI6MTU4OTUyMDA0MH0.hVGQm9nLVxdpEdmcSmD02VsV4saedrPLSuUc_HQgkhI"
}
