POST http://localhost:5000/stories
Content-Type: application/json

{   
    "title": "Story A",
    "body":"body A",
    "userId": "5ebae15e4810562480e6baf6"
}

###
GET http://localhost:5000/stories
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZWJiMDE3MzQ5YWU0OTYxNGM2YWFkYjIiLCJ1c2VyX25hbWUiOiJBIiwiZW1haWwiOiJhYUB0ZXN0LmNvbSIsImlhdCI6MTU4OTM4OTY4NiwiZXhwIjoxNTg5NDc2MDg2fQ.ab4tF4UORaqYJWO-0Firia_R8zkASYKtHeaNUSkXdPE

###
GET http://localhost:5000/stories/author?author=Dhas&page=1&limit=3

###
PUT http://localhost:5000/stories
Content-Type: application/json

{
    "body":"work 1",
    "id": "5eb587fc0428ab590cbcea91",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZWJiMDE3MzQ5YWU0OTYxNGM2YWFkYjIiLCJ1c2VyX25hbWUiOiJBIiwiZW1haWwiOiJhYUB0ZXN0LmNvbSIsImlhdCI6MTU4OTM4OTY4NiwiZXhwIjoxNTg5NDc2MDg2fQ.ab4tF4UORaqYJWO-0Firia_R8zkASYKtHeaNUSkXdPE"
}

###
DELETE http://localhost:5000/stories
Content-Type: application/json

{
    "_id": "5eb66a9e2cdfc82e380b807e"
}



