POST http://localhost:5000/stories
Content-Type: application/json

{   
    "title": "Story E",
    "body":" Body 5 ",
    "author":"E"
}

###
GET http://localhost:5000/stories

###
GET http://localhost:5000/stories/author?author=Dhas&page=1&limit=3

###
PUT http://localhost:5000/stories
Content-Type: application/json

{
    "body":"Work 1",
    "id": "5eb907be9b27e32354a5750a"
}

###
DELETE http://localhost:5000/stories
Content-Type: application/json

{
    "_id": "5eb907be9b27e32354a5750a"
}



