POST http://localhost:5000/stories
Content-Type: application/json

{   
    "title": "Home 1",
    "body":"work 1",
    "author":"GRS"
}

###
GET http://localhost:5000/stories?page=1&limit=3

###
GET http://localhost:5000/stories/author?author=Dhas&page=1&limit=3

###
PUT http://localhost:5000/stories
Content-Type: application/json

{
    "body":"Hello World Testing!",
    "id": "5eb4720ea8dae0556cb7b7dd"
}

###
DELETE http://localhost:5000/stories
Content-Type: application/json

{
    "body":"Hello World Testing!",
    "id": "5eb441cf0dc3513ff4cfde39"
}


// UserData
### 
POST http://localhost:5000/users/register
Content-Type: application/json

{
    "first_name": "Bob",
    "last_name": "Dylan",
    "email": "test@test.com",
    "password": "test"
}

### 
POST http://localhost:5000/users/login
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "test" 
}

###
GET http://localhost:5000/users/login
