### 
POST http://localhost:5000/users/register
Content-Type: application/json

{
    "user_name": "E",
    "email": "ee@test.com",
    "password": "ee"
}

### 
POST http://localhost:5000/users/login
Content-Type: application/json

{
    "email": "aa@test.com",
    "password": "aa" 
}

###
GET http://localhost:5000/users/profile
